name: Build and Test

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Install CMake and dependencies
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential

    # Step 3: Cache CMake build
    - name: Cache CMake build
      uses: actions/cache@v3
      with:
        path: |
          build
          ~/.cmake
          ~/.cache
        key: ${{ runner.os }}-cmake-${{ hashFiles('**/CMakeLists.txt') }}
        restore-keys: |
          ${{ runner.os }}-cmake-

    # Step 4: Build the project
    - name: Build project
      run: |
        mkdir -p build
        cd build
        cmake ..
        make

    # Step 5: Check if build was successful
    - name: Verify build success
      run: echo "Build succeeded"
